CREATE TABLE IF NOT EXISTS images (
	uuid UUID     NOT NULL PRIMARY KEY,
	NAME           TEXT    NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)